##
# Dockerfile.ubuntu 를 활용한 custom docker file
#   Dockerfile.ubuntu : 변하지 않을 과정으로 확정된 부분을 미리 생성한 것
#   Dockerfile.custom : 반복적으로 추가/변경/삭제 할 부분
##

FROM            elass_ubuntu
MAINTAINER      bbungsang@gmail.com