# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.myuser
import utils.fields.custom_image_fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.myuser.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_photo',
            field=utils.fields.custom_image_fields.CustomImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('d', 'Django'), ('f', 'Facebook')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
