# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170909_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(max_length=20, null=True)),
                ('cert_photo', models.ImageField(null=True, upload_to='user/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('univ', '대학인증'), ('grad', '대학원인증'), ('identity', '신분증인증')], max_length=8)),
                ('school', models.CharField(blank=True, max_length=20)),
                ('major', models.CharField(max_length=20, null=True)),
                ('status_type', models.CharField(choices=[('ing', '재학'), ('graduation', '졸업'), ('complete', '수료')], max_length=10, null=True)),
                ('identification', models.ImageField(null=True, upload_to='user/%Y/%m/%d')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='member.Tutor'),
        ),
    ]
